insert into Countries
select 'Afghanistan'
union select 'Albania'
union select 'Algeria'
union select 'Andorra'
union select 'Angola'
union select 'Antigua and Barbuda'
union select 'Argentina'
union select 'Armenia'
union select 'Australia'
union select 'Austria'
union select 'Azerbaijan'
union select 'Bahamas'
union select 'Bahrain'
union select 'Bangladesh'
union select 'Barbados'
union select 'Belarus'
union select 'Belgium'
union select 'Belize'
union select 'Benin'
union select 'Bhutan'
union select 'Bolivia, Plurinational State of'
union select 'Bosnia and Herzegovina'
union select 'Botswana'
union select 'Brazil'
union select 'Brunei Darussalam'
union select 'Bulgaria'
union select 'Burkina Faso'
union select 'Burundi'
union select 'Cabo Verde'
union select 'Cambodia'
union select 'Cameroon'
union select 'Canada'
union select 'Central African Republic'
union select 'Chad'
union select 'Chile'
union select 'China'
union select 'Colombia'
union select 'Comoros'
union select 'Congo'
union select 'Congo, Democratic Republic of the'
union select 'Costa Rica'
union select 'Côte d''Ivoire'
union select 'Croatia'
union select 'Cuba'
union select 'Cyprus'
union select 'Czechia'
union select 'Denmark'
union select 'Djibouti'
union select 'Dominica'
union select 'Dominican Republic'
union select 'Ecuador'
union select 'Egypt'
union select 'El Salvador'
union select 'Equatorial Guinea'
union select 'Eritrea'
union select 'Estonia'
union select 'Eswatini'
union select 'Ethiopia'
union select 'Fiji'
union select 'Finland'
union select 'France'
union select 'Gabon'
union select 'Gambia'
union select 'Georgia'
union select 'Germany'
union select 'Ghana'
union select 'Greece'
union select 'Grenada'
union select 'Guatemala'
union select 'Guinea'
union select 'Guinea-Bissau'
union select 'Guyana'
union select 'Haiti'
union select 'Honduras'
union select 'Hungary'
union select 'Iceland'
union select 'India'
union select 'Indonesia'
union select 'Iran, Islamic Republic of'
union select 'Iraq'
union select 'Ireland'
union select 'Israel'
union select 'Italy'
union select 'Jamaica'
union select 'Japan'
union select 'Jordan'
union select 'Kazakhstan'
union select 'Kenya'
union select 'Kiribati'
union select 'Korea, Democratic People''s Republic of'
union select 'Korea, Republic of'
union select 'Kuwait'
union select 'Kyrgyzstan'
union select 'Lao People''s Democratic Republic'
union select 'Latvia'
union select 'Lebanon'
union select 'Lesotho'
union select 'Liberia'
union select 'Libya'
union select 'Liechtenstein'
union select 'Lithuania'
union select 'Luxembourg'
union select 'Madagascar'
union select 'Malawi'
union select 'Malaysia'
union select 'Maldives'
union select 'Mali'
union select 'Malta'
union select 'Marshall Islands'
union select 'Mauritania'
union select 'Mauritius'
union select 'Mexico'
union select 'Micronesia, Federated States of'
union select 'Moldova, Republic of'
union select 'Monaco'
union select 'Mongolia'
union select 'Montenegro'
union select 'Morocco'
union select 'Mozambique'
union select 'Myanmar'
union select 'Namibia'
union select 'Nauru'
union select 'Nepal'
union select 'Netherlands'
union select 'New Zealand'
union select 'Nicaragua'
union select 'Niger'
union select 'Nigeria'
union select 'North Macedonia'
union select 'Norway'
union select 'Oman'
union select 'Pakistan'
union select 'Palau'
union select 'Panama'
union select 'Papua New Guinea'
union select 'Paraguay'
union select 'Peru'
union select 'Philippines'
union select 'Poland'
union select 'Portugal'
union select 'Qatar'
union select 'Romania'
union select 'Russian Federation'
union select 'Rwanda'
union select 'Saint Kitts and Nevis'
union select 'Saint Lucia'
union select 'Saint Vincent and the Grenadines'
union select 'Samoa'
union select 'San Marino'
union select 'São Tomé and Príncipe'
union select 'Saudi Arabia'
union select 'Senegal'
union select 'Serbia'
union select 'Seychelles'
union select 'Sierra Leone'
union select 'Singapore'
union select 'Slovakia'
union select 'Slovenia'
union select 'Solomon Islands'
union select 'Somalia'
union select 'South Africa'
union select 'South Sudan'
union select 'Spain'
union select 'Sri Lanka'
union select 'Sudan'
union select 'Suriname'
union select 'Sweden'
union select 'Switzerland'
union select 'Syrian Arab Republic'
union select 'Taiwan'
union select 'Tajikistan'
union select 'Tanzania, United Republic of'
union select 'Thailand'
union select 'Timor-Leste'
union select 'Togo'
union select 'Tonga'
union select 'Trinidad and Tobago'
union select 'Tunisia'
union select 'Türkiye'
union select 'Turkmenistan'
union select 'Tuvalu'
union select 'Uganda'
union select 'Ukraine'
union select 'United Arab Emirates'
union select 'United Kingdom of Great Britain and Northern Ireland'
union select 'United States of America'
union select 'Uruguay'
union select 'Uzbekistan'
union select 'Vatican City'
union select 'Vanuatu'
union select 'Venezuela, Bolivarian Republic of'
union select 'Vietnam'
union select 'Yemen'
union select 'Zambia'
union select 'Zimbabwe'


-- Update to get simple names

update	Country
set		Name = 'Bolivia'
where	Name like '%Bolivia%'

update	Country
set		Name = 'Brunei'
where	Name like '%Brunei%'

update	Country
set		Name = 'Democratic Republic of the Congo'
where	Name = 'Congo, Democratic Republic of the'

update	Country
set		Name = 'Republic of the Congo'
where	Name = 'Congo'

update	Country
set		Name = 'Iran'
where	Name like '%Iran%'

update	Country
set		Name = 'North Korea'
where	Name like '%Korea, Democratic%'

update	Country
set		Name = 'South Korea'
where	Name like '%Korea, Republic%'

update	Country
set		Name = 'Laos'
where	Name like '%Lao People%'

update	Country
set		Name = 'Micronesia'
where	Name like '%Micronesia%'

update	Country
set		Name = 'Moldova'
where	Name like '%Moldova%'

update	Country
set		Name = 'Russia'
where	Name like '%Russia%'

update	Country
set		Name = 'Syria'
where	Name like '%Syria%'

update	Country
set		Name = 'Tanzania'
where	Name like '%Tanzania%'

update	Country
set		Name = 'Turkey'
where	Name like '%Türkiye%'

update	Country
set		Name = 'United Kingdom'
where	Name like '%United Kingdom%'

update	Country
set		Name = 'Venezuela'
where	Name like '%Venezuela%'